"""
Default definitions for top-level library categories.
"""
from typing import Any, Dict, List


def get_default_library_categories() -> List[Dict[str, Any]]:
    return [
        {
            "slug": "guided-meditations",
            "title": "Guided Meditations",
            "description": "Calming guided practices for beginners and seasoned meditators alike.",
            "accent_color": "#2F695C",
            "icon": "feather",
            "cover_image_url": "https://images.unsplash.com/photo-1529101091764-c3526daf38fe?auto=format&fit=crop&w=1200&q=80",
            "order_index": 1,
            "is_active": True,
            "tags": ["meditation", "calm", "beginner"],
            "metadata_": {
                "subcategories": [
                    "For beginners",
                    "Stress relief",
                    "Focus sessions",
                    "Sleep",
                    "Loving-kindness",
                    "Anxiety support",
                ],
                "featured_format": "audio",
            },
        },
        {
            "slug": "breathwork-body-practices",
            "title": "Breathwork & Body Practices",
            "description": "Grounding movement, breathing exercises, and embodied mindfulness.",
            "accent_color": "#1E6C67",
            "icon": "wind",
            "cover_image_url": "https://images.unsplash.com/photo-1587837073080-448bc6a2329b?auto=format&fit=crop&w=1200&q=80",
            "order_index": 2,
            "is_active": True,
            "tags": ["breathwork", "movement", "body"],
            "metadata_": {
                "subcategories": [
                    "Breathing exercises",
                    "Body scan",
                    "Mindful movement",
                    "Yoga flows",
                    "Progressive relaxation",
                ],
                "featured_format": "audio",
            },
        },
        {
            "slug": "sleep-relaxation",
            "title": "Sleep & Relaxation",
            "description": "Wind-down rituals, dreamy soundscapes, and stories for restorative rest.",
            "accent_color": "#3F5EAB",
            "icon": "moon",
            "cover_image_url": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
            "order_index": 3,
            "is_active": True,
            "tags": ["sleep", "relaxation", "insomnia"],
            "metadata_": {
                "subcategories": [
                    "Sleep stories",
                    "Sleep music",
                    "Guided sleep meditations",
                    "Insomnia support",
                ],
                "featured_format": "story",
            },
        },
        {
            "slug": "focus-productivity",
            "title": "Focus & Productivity",
            "description": "Mindful tools to sharpen attention, flow, and creative energy.",
            "accent_color": "#35607E",
            "icon": "target",
            "cover_image_url": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80",
            "order_index": 4,
            "is_active": True,
            "tags": ["focus", "productivity", "work"],
            "metadata_": {
                "subcategories": [
                    "Work and study focus",
                    "Creativity boosts",
                    "Digital detox",
                    "Mindful breaks",
                ],
                "featured_format": "article",
            },
        },
        {
            "slug": "emotional-wellbeing",
            "title": "Emotional Wellbeing",
            "description": "Practices for resilience, compassion, and steady emotional regulation.",
            "accent_color": "#B2516E",
            "icon": "heart",
            "cover_image_url": "https://images.unsplash.com/photo-1523978591478-c753949ff840?auto=format&fit=crop&w=1200&q=80",
            "order_index": 5,
            "is_active": True,
            "tags": ["emotions", "resilience", "calm"],
            "metadata_": {
                "subcategories": [
                    "Mindfulness for anxiety",
                    "Managing depression",
                    "Emotional regulation",
                    "Self-compassion",
                ],
                "featured_format": "audio",
            },
        },
        {
            "slug": "mini-emergency-practices",
            "title": "Mini & Emergency Practices",
            "description": "Rapid resets and SOS support when you need relief in under five minutes.",
            "accent_color": "#D07A2D",
            "icon": "zap",
            "cover_image_url": "https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80",
            "order_index": 6,
            "is_active": True,
            "tags": ["quick", "sos", "reset"],
            "metadata_": {
                "subcategories": [
                    "Under 5 minutes",
                    "Emergency calm downs",
                    "Quick resets",
                ],
                "featured_format": "audio",
            },
        },
        {
            "slug": "mindful-living",
            "title": "Mindful Living",
            "description": "Everyday rituals to weave mindfulness into habits, home, and relationships.",
            "accent_color": "#3F7E44",
            "icon": "home",
            "cover_image_url": "https://images.unsplash.com/photo-1511988617509-a57c8a288659?auto=format&fit=crop&w=1200&q=80",
            "order_index": 7,
            "is_active": True,
            "tags": ["lifestyle", "habit", "gratitude"],
            "metadata_": {
                "subcategories": [
                    "Gratitude",
                    "Mindful eating",
                    "Self-discovery",
                    "Daily routines",
                    "Healthy habits",
                ],
                "featured_format": "article",
            },
        },
        {
            "slug": "courses-series",
            "title": "Courses & Series",
            "description": "Structured programs and thematic journeys to deepen your practice.",
            "accent_color": "#6C4FB4",
            "icon": "book-open",
            "cover_image_url": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
            "order_index": 8,
            "is_active": True,
            "tags": ["course", "challenge", "learning"],
            "metadata_": {
                "subcategories": [
                    "Multi-day challenges",
                    "Foundational courses",
                    "Themed journeys",
                ],
                "featured_format": "multi-day",
            },
        },
        {
            "slug": "soundscapes-music",
            "title": "Soundscapes & Music",
            "description": "Immersive nature sounds, binaural beats, and ambient mixes to reset your nervous system.",
            "accent_color": "#294E67",
            "icon": "music",
            "cover_image_url": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
            "order_index": 9,
            "is_active": True,
            "tags": ["soundscape", "music", "nature"],
            "metadata_": {
                "subcategories": [
                    "Nature sounds",
                    "Binaural beats",
                    "Rain and ocean",
                    "Forest ambience",
                ],
                "featured_format": "audio",
            },
        },
        {
            "slug": "articles-resources",
            "title": "Articles & Resources",
            "description": "Quick reads and deep dives covering mindfulness, wellbeing, and sleep science.",
            "accent_color": "#546E7A",
            "icon": "file-text",
            "cover_image_url": "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=1200&q=80",
            "order_index": 10,
            "is_active": True,
            "tags": ["article", "education", "research"],
            "metadata_": {
                "subcategories": [
                    "Mindfulness insights",
                    "Wellness tips",
                    "Sleep health",
                    "Self-care guides",
                ],
                "featured_format": "article",
            },
        },
        {
            "slug": "kids-families",
            "title": "For Kids & Families",
            "description": "Wholesome practices for little ones, mindful parenting, and family bedtime routines.",
            "accent_color": "#D78234",
            "icon": "users",
            "cover_image_url": "https://images.unsplash.com/photo-1503455637927-730bce8583c0?auto=format&fit=crop&w=1200&q=80",
            "order_index": 11,
            "is_active": True,
            "tags": ["family", "kids", "parenting"],
            "metadata_": {
                "subcategories": [
                    "Family mindfulness",
                    "Mindful parenting",
                    "Bedtime routines for kids",
                ],
                "featured_format": "story",
            },
        },
    ]


